name: Run Ubuntu.sh in Parallel

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes to restart the instances
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-ubuntu-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    timeout-minutes: 22  # Ensures the job doesn't run forever
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Download Ubuntu.sh
        run: wget -O ubuntu.sh https://raw.githubusercontent.com/brownbooks/MyPersonal/main/Ubuntu.sh
      
      - name: Set Execution Permissions
        run: chmod +x ubuntu.sh
      
      - name: Run Ubuntu.sh
        run: |
          nohup ./ubuntu.sh &
          sleep 1200  # Let it run for 20 minutes
      
      - name: Terminate Process
        run: |
          pkill -f ubuntu.sh || echo "Process already terminated"
      
      - name: Cleanup & Restart Workflow
        if: always()
        run: echo "Instance ${{ matrix.instance }} completed, waiting for next scheduled run."
